name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USERNAME}} #Private or public key of the server
         
          script: |
            rm -rf backend_ludo
            rm -rf new
            pm2 kill
            git clone -b main git@github.com:practice5610/backend_ludo.git
            mkdir new
            mv backend_ludo/built new/
            rm -rf backend_ludo
            cd new
            cd built
            npm install pm2 -g
            pm2 start index.js
            sudo service nginx restart
            sudo systemctl reload nginx
            echo 'Deployment successful to DigitalOcean'
