name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          env:
            ENV_FILE: ${{ secrets.ENV_FILE }}

          script: |
            git clone git@github.com:practice5610/backend_ludo.git
            cd backend_ludo
            npm install
            npm run build
            cd built
            npm install pm2 -g
            pm2 start index.js

      - name: Echo Deployment successful
        run: echo 'Deployment successful to DigitalOcean'
